name: 构建推送

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set GITHUB_ENV
        run: |
          echo "VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
          echo "DOCKER_HUB_TAG=$(curl --silent https://registry.hub.docker.com/v2/repositories/qvgz/caddy/tags | jq -r '.results | .[1] | .name')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:caddy"
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            qvgz/caddy:latest
            qvgz/caddy:${{ env.VERSION }}
  supervisord:
    runs-on: ubuntu-latest
    steps:
      - name: Set GITHUB_ENV
        run: |
          echo "VERSION=$(curl --silent "https://api.github.com/repos/ochinchina/supervisord/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
          echo "DOCKER_HUB_TAG=$(curl --silent https://registry.hub.docker.com/v2/repositories/qvgz/supervisord/tags | jq -r '.results | .[1] | .name')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:supervisord"
          build-args: VERSION=${{ env.VERSION }}
          file: ./Dockerfile
          push: true
          tags: |
            qvgz/supervisord:latest
            qvgz/supervisord:${{ env.VERSION }}
